/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.mysurya;
import id.mysurya.input.Input;
import id.mysurya.output.HLine;
import id.mysurya.output.Space;
import id.mysurya.output.Label;
import id.mysurya.input.SelectInput;
import id.mysurya.page.MainPage;
import id.mysurya.storage.DataPassword;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        DataPassword.loadCSVData();
        new MainPage("Enkrip Password Store", 80).draw();
    }
}
